name: Build CSS Bundle

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install

      - name: Bundle
        run: npm run build

      - name: Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "77406318+github-actions[bot]@users.noreply.github.com"
          git add -f ./cacsscade.min.css
          git commit -m "build ${{ github.sha }} bundle"
          git push
